### ISSUE TITLE
Question on the algorithm of tracking ?

### ISSUE THREAD

**Issue by hoangkhoiLE** [kodamap/person_reidentification#1]
Hello,

Thank for your excellent work. What is the algorithm of tracking that you used ?

Best regard

**Comment by kodamap** [comment]
Thank you for your comment.

I used `Cosine similarity`, `Intersection over Union (IoU)` , `Euclidean distance` while tracking.
Tracking flow is like this. (Please see `tracking.py`)

1. Check cosine similarity per each frame
OpenVINO `person re-identification` model gives you a person's feature vector in the frame.
You get cosine similarity from person's feature vectors in current and previous frame.
If the cosine similarity is high (I think about 0.6 seems to be good), you can treat them as the same person.

2. Exclusion conditions of tracking
To maintain high quality feature vectors, do not keep the feature vectors when persons are overlapped.  I used `IoU` to avoid this occlusion problem.

3. Keep identity by compound condition
Even if the cosine similarity is low, keep the identity when the distance (`Euclidean distance`) between the center points of the current and previous person frame  are close.

4. Do not keep unnecessary information
To improve the comparison accuracy of feature vectors,  remove tracking information of the person who has gone out of frame 

5. Finally register the person
Register the person vector as a new person If the above conditions are not met.

I hope this helps.

**Comment by hoangkhoiLE** [comment]
Thank you for your answer.

**Comment by hoangkhoiLE** [comment]
Just one question, why you don't want to use deep sort ? Will algorithm tracking get better result ?

**Comment by kodamap** [comment]
I appreciate your information. I didn't know "Deep Sort". 

I tried it with [LeonLok/Deep-SORT-YOLOv4](https://github.com/LeonLok/Deep-SORT-YOLOv4/tree/master/tensorflow2.0/deep-sort-yolov4). As you said it's better way of tracking objects! 
But it seems to be difficult to use on **CPU** environment when real-time tracking. (I got poor frame rate : 0.5 fps)

**Comment by hoangkhoiLE** [comment]
Yes but it's good to give a test on openvino :+1:
