### ISSUE TITLE
Random ids are being assigned to Persons

### ISSUE THREAD

**Issue by peeyush-quantela** [kodamap/person_reidentification#4]
I tried to run the solution on the Oxford Town Centre Video Sample (Link: https://www.kaggle.com/ashayajbani/oxford-town-centre?select=TownCentreXVID.mp4), but the persons get random ids. Could you please help in setting up the correct parameters, if that can improve the result?

**Comment by kodamap** [comment]
I am really sorry for the late reply and thank you for your comments. 
This problem cannot be solved by just changing the parameters, I need to come up with a new way.
It is very difficult for me, but I am working on this problem now...

**Comment by kodamap** [comment]
Fixed and will close.
